### ISSUE TITLE
enable github-org-entity-provider plugin

### ISSUE THREAD

**Issue by durandom** [b4mad/racing-developer-hub#1]
Following docs at https://access.redhat.com/documentation/en-us/red_hat_developer_hub/1.0/html/getting_started_with_red_hat_developer_hub/ref-rhdh-supported-configs_rhdh-getting-started#enabling-github-organization-member-discovery-in-red-hat-developer-hub

```
Loading config from MergedConfigSource{FileConfigSource{path="/opt/app-root/src/app-config.yaml"}, FileConfigSource{path="/opt/app-root/src/app-config.example.yaml"}, FileConfigSource{path="/opt/app-root/src/app-config.example.production.yaml"}, FileConfigSource{path="/opt/app-root/src/dynamic-plugins-root/app-config.dynamic-plugins.yaml"}, FileConfigSource{path="/opt/app-root/src/app-config-rhdh.yaml"}, FileConfigSource{path="/opt/app-root/src/app-config-from-configmap.yaml"}, EnvConfigSource{count=1}}
(node:1) MaxListenersExceededWarning: Possible EventTarget memory leak detected. 11 abort listeners added to [AbortSignal]. Use events.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
skipping '/opt/app-root/src/dynamic-plugins-root/app-config.dynamic-plugins.yaml' since it is not a directory
[2m2024-03-07T11:23:29.333Z[22m [34mbackstage[39m [32minfo[39m Found 6 new secrets in config that will be redacted 
[2m2024-03-07T11:23:29.336Z[22m [34mbackstage[39m [32minfo[39m skipping '/opt/app-root/src/dynamic-plugins-root/app-config.dynamic-plugins.yaml' since it is not a directory 
[2m2024-03-07T11:23:29.375Z[22m [34mbackstage[39m [32minfo[39m loaded dynamic backend plugin 'backstage-plugin-catalog-backend-module-github-dynamic' from 'file:///opt/app-root/src/dynamic-plugins-root/backstage-plugin-catalog-backend-module-github-dynamic-0.5.2' 
[2m2024-03-07T11:23:29.423Z[22m [34mbackstage[39m [32minfo[39m loaded dynamic backend plugin 'backstage-plugin-catalog-backend-module-github-org-dynamic' from 'file:///opt/app-root/src/dynamic-plugins-root/backstage-plugin-catalog-backend-module-github-org-dynamic-0.1.6' 
[2m2024-03-07T11:23:29.531Z[22m [34mbackstage[39m [32minfo[39m loaded dynamic backend plugin 'backstage-plugin-scaffolder-backend-module-azure-dynamic' from 'file:///opt/app-root/src/dynamic-plugins-root/backstage-plugin-scaffolder-backend-module-azure-dynamic-0.1.4' 
[2m2024-03-07T11:23:29.574Z[22m [34mbackstage[39m [32minfo[39m loaded dynamic backend plugin 'backstage-plugin-scaffolder-backend-module-bitbucket-cloud-dynamic' from 'file:///opt/app-root/src/dynamic-plugins-root/backstage-plugin-scaffolder-backend-module-bitbucket-cloud-dynamic-0.1.2' 
[2m2024-03-07T11:23:29.600Z[22m [34mbackstage[39m [32minfo[39m loaded dynamic backend plugin 'backstage-plugin-scaffolder-backend-module-bitbucket-server-dynamic' from 'file:///opt/app-root/src/dynamic-plugins-root/backstage-plugin-scaffolder-backend-module-bitbucket-server-dynamic-0.1.2' 
[2m2024-03-07T11:23:29.641Z[22m [34mbackstage[39m [32minfo[39m loaded dynamic backend plugin 'backstage-plugin-scaffolder-backend-module-gerrit-dynamic' from 'file:///opt/app-root/src/dynamic-plugins-root/backstage-plugin-scaffolder-backend-module-gerrit-dynamic-0.1.4' 
[2m2024-03-07T11:23:29.759Z[22m [34mbackstage[39m [32minfo[39m loaded dynamic backend plugin 'backstage-plugin-scaffolder-backend-module-github-dynamic' from 'file:///opt/app-root/src/dynamic-plugins-root/backstage-plugin-scaffolder-backend-module-github-dynamic-0.2.2' 
[2m2024-03-07T11:23:29.896Z[22m [34mbackstage[39m [32minfo[39m loaded dynamic backend plugin 'backstage-plugin-scaffolder-backend-module-gitlab-dynamic' from 'file:///opt/app-root/src/dynamic-plugins-root/backstage-plugin-scaffolder-backend-module-gitlab-dynamic-0.2.15' 
[2m2024-03-07T11:23:30.454Z[22m [34mbackstage[39m [32minfo[39m loaded dynamic backend plugin 'backstage-plugin-techdocs-backend-dynamic' from 'file:///opt/app-root/src/dynamic-plugins-root/backstage-plugin-techdocs-backend-dynamic-1.9.5' 
[2m2024-03-07T11:23:30.455Z[22m [34mbackstage[39m [32minfo[39m loaded dynamic backend plugin '@janus-idp/backstage-scaffolder-backend-module-quay-dynamic' from 'file:///opt/app-root/src/dynamic-plugins-root/janus-idp-backstage-scaffolder-backend-module-quay-dynamic-1.3.4/alpha' 
[2m2024-03-07T11:23:30.494Z[22m [34mbackstage[39m [32minfo[39m loaded dynamic backend plugin '@janus-idp/backstage-scaffolder-backend-module-regex-dynamic' from 'file:///opt/app-root/src/dynamic-plugins-root/janus-idp-backstage-scaffolder-backend-module-regex-dynamic-1.3.4/alpha' 
[2m2024-03-07T11:23:30.566Z[22m [34mbackstage[39m [32minfo[39m loaded dynamic backend plugin 'roadiehq-scaffolder-backend-module-utils-dynamic' from 'file:///opt/app-root/src/dynamic-plugins-root/roadiehq-scaffolder-backend-module-utils-dynamic-1.13.6' 
[2m2024-03-07T11:23:30.578Z[22m [34mrootHttpRouter[39m [32minfo[39m Listening on :7007 
[2m2024-03-07T11:23:30.603Z[22m [34mauth[39m [32minfo[39m Enabled Provider Factories : {} 
[2m2024-03-07T11:23:30.621Z[22m [34mscalprum[39m [32minfo[39m Loaded dynamic frontend plugin 'backstage-plugin-techdocs' from 'file:///opt/app-root/src/dynamic-plugins-root/backstage-plugin-techdocs-1.10.0'  
[2m2024-03-07T11:23:30.626Z[22m [34mproxy[39m [32minfo[39m [HPM] Proxy created: /quay/api  -> https://quay.io/ 
[2m2024-03-07T11:23:30.627Z[22m [34mproxy[39m [32minfo[39m [HPM] Proxy rewrite rule created: "^/api/proxy/quay/api/?" ~> "/" 
[2m2024-03-07T11:23:30.628Z[22m [34mproxy[39m [33mwarn[39m skipped configuring /sonarqube due to Proxy target for route "/sonarqube" must be a string, but is of type undefined 
[2m2024-03-07T11:23:30.628Z[22m [34mproxy[39m [33mwarn[39m skipped configuring /jenkins/api due to Proxy target for route "/jenkins/api" must be a string, but is of type undefined 
[2m2024-03-07T11:23:30.628Z[22m [34mproxy[39m [33mwarn[39m skipped configuring /jira/api due to Proxy target for route "/jira/api" must be a string, but is of type undefined 
[2m2024-03-07T11:23:30.628Z[22m [34mproxy[39m [33mwarn[39m skipped configuring /acr/api due to Proxy target for route "/acr/api" must be a string, but is of type undefined 
[2m2024-03-07T11:23:30.628Z[22m [34mproxy[39m [33mwarn[39m skipped configuring /jfrog-artifactory/api due to Proxy target for route "/jfrog-artifactory/api" must be a string, but is of type undefined 
[2m2024-03-07T11:23:30.628Z[22m [34mproxy[39m [32minfo[39m [HPM] Proxy created: /pagerduty  -> https://api.pagerduty.com 
[2m2024-03-07T11:23:30.628Z[22m [34mproxy[39m [32minfo[39m [HPM] Proxy rewrite rule created: "^/api/proxy/pagerduty/?" ~> "/" 
[2m2024-03-07T11:23:30.629Z[22m [34mproxy[39m [33mwarn[39m skipped configuring /dynatrace due to Proxy target for route "/dynatrace" must be a string, but is of type undefined 
[2m2024-03-07T11:23:30.629Z[22m [34mproxy[39m [33mwarn[39m skipped configuring /nexus-repository-manager due to Proxy target for route "/nexus-repository-manager" must be a string, but is of type undefined 
[2m2024-03-07T11:23:30.629Z[22m [34mproxy[39m [32minfo[39m [HPM] Proxy created: /developer-hub  -> https://raw.githubusercontent.com/ 
[2m2024-03-07T11:23:30.629Z[22m [34mproxy[39m [32minfo[39m [HPM] Proxy rewrite rule created: "^/api/proxy/developer-hub" ~> "/b4mad/racing-developer-hub/main/app/public/homepage/data.json" 
[2m2024-03-07T11:23:30.635Z[22m [34mtechdocs[39m [32minfo[39m Creating Local publisher for TechDocs 
[2m2024-03-07T11:23:30.661Z[22m [34mauth[39m [32minfo[39m Configuring "database" as KeyStore provider 
[2m2024-03-07T11:23:30.669Z[22m [34mscaffolder[39m [32minfo[39m Starting scaffolder with the following actions enabled quay:create-repository, regex:replace, publish:azure, publish:bitbucketCloud, bitbucket:pipelines:run, publish:bitbucketServer, publish:bitbucketServer:pull-request, publish:gerrit, publish:gerrit:review, github:actions:dispatch, github:autolinks:create, github:deployKey:create, github:environment:create, github:issues:label, github:repo:create, github:repo:push, github:webhook, publish:github, publish:github:pull-request, gitlab:group:ensureExists, gitlab:issues:create, gitlab:projectAccessToken:create, gitlab:projectDeployToken:create, gitlab:projectVariable:create, gitlab:repo:push, publish:gitlab, publish:gitlab:merge-request, roadiehq:utils:zip, roadiehq:utils:sleep, roadiehq:utils:fs:write, roadiehq:utils:fs:append, roadiehq:utils:json:merge, roadiehq:utils:merge, roadiehq:utils:fs:parse, roadiehq:utils:fs:replace, roadiehq:utils:serialize:yaml, roadiehq:utils:serialize:json, roadiehq:utils:jsonata, roadiehq:utils:jsonata:yaml:transform, roadiehq:utils:jsonata:json:transform, fetch:plain, fetch:plain:file, fetch:template, debug:log, debug:wait, catalog:register, catalog:fetch, catalog:write, fs:delete, fs:rename 
[2m2024-03-07T11:23:30.672Z[22m [34msearch[39m [32minfo[39m Added DefaultCatalogCollatorFactory collator factory for type software-catalog 
[2m2024-03-07T11:23:30.672Z[22m [34msearch[39m [32minfo[39m Added DefaultTechDocsCollatorFactory collator factory for type techdocs 
[2m2024-03-07T11:23:30.672Z[22m [34msearch[39m [32minfo[39m Starting all scheduled search tasks. 
/opt/app-root/src/node_modules/@backstage/backend-app-api/dist/index.cjs.js:1781
              throw new errors.ForwardedError(
                    ^

ForwardedError: Module 'github-org-entity-provider' for plugin 'catalog' startup failed; caused by Error: Missing required config value at 'catalog.providers.githubOrg.githubUrl'
    at /opt/app-root/src/node_modules/@backstage/backend-app-api/dist/index.cjs.js:1781:21
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /opt/app-root/src/node_modules/@backstage/backend-app-api/dist/index.cjs.js:1780:13
    at async processNode (/opt/app-root/src/node_modules/@backstage/backend-app-api/dist/index.cjs.js:1302:22)
    ... 6 lines matching cause stack trace ...
    at async BackendInitializer.start (/opt/app-root/src/node_modules/@backstage/backend-app-api/dist/index.cjs.js:1611:5)
    at async BackstageBackend.start (/opt/app-root/src/node_modules/@backstage/backend-app-api/dist/index.cjs.js:1881:5) {
  cause: Error: Missing required config value at 'catalog.providers.githubOrg.githubUrl'
      at ConfigReader.getString (/opt/app-root/src/node_modules/@backstage/config/dist/index.cjs.js:305:13)
      at ObservableConfigProxy.getString (/opt/app-root/src/node_modules/@backstage/config-loader/dist/index.cjs.js:1348:30)
      at /opt/app-root/src/dynamic-plugins-root/backstage-plugin-catalog-backend-module-github-org-dynamic-0.1.6/dist/index.cjs.js:2561:19
      at Array.map (<anonymous>)
      at readDefinitionsFromConfig (/opt/app-root/src/dynamic-plugins-root/backstage-plugin-catalog-backend-module-github-org-dynamic-0.1.6/dist/index.cjs.js:2559:19)
      at Object.init [as func] (/opt/app-root/src/dynamic-plugins-root/backstage-plugin-catalog-backend-module-github-org-dynamic-0.1.6/dist/index.cjs.js:2533:35)
      at /opt/app-root/src/node_modules/@backstage/backend-app-api/dist/index.cjs.js:1780:35
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async processNode (/opt/app-root/src/node_modules/@backstage/backend-app-api/dist/index.cjs.js:1302:22)
      at async Promise.all (index 3)
      at async processMoreNodes (/opt/app-root/src/node_modules/@backstage/backend-app-api/dist/index.cjs.js:1297:7)
      at async _DependencyGraph.parallelTopologicalTraversal (/opt/app-root/src/node_modules/@backstage/backend-app-api/dist/index.cjs.js:1308:5)
      at async /opt/app-root/src/node_modules/@backstage/backend-app-api/dist/index.cjs.js:1777:9
      at async Promise.all (index 1)
      at async BackendInitializer.doStart_fn (/opt/app-root/src/node_modules/@backstage/backend-app-api/dist/index.cjs.js:1757:3)
      at async BackendInitializer.start (/opt/app-root/src/node_modules/@backstage/backend-app-api/dist/index.cjs.js:1611:5)
}

Node.js v18.18.2
```

**Comment by durandom** [comment]
```
/opt/app-root/src/node_modules/@backstage/backend-app-api/dist/index.cjs.js:1781
              throw new errors.ForwardedError(
                    ^

ForwardedError: Module 'github-org-entity-provider' for plugin 'catalog' startup failed; caused by Error: Missing required config value at 'catalog.providers.githubOrg.githubUrl'
    at /opt/app-root/src/node_modules/@backstage/backend-app-api/dist/index.cjs.js:1781:21
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /opt/app-root/src/node_modules/@backstage/backend-app-api/dist/index.cjs.js:1780:13
    at async processNode (/opt/app-root/src/node_modules/@backstage/backend-app-api/dist/index.cjs.js:1302:22)
    ... 6 lines matching cause stack trace ...
    at async BackendInitializer.start (/opt/app-root/src/node_modules/@backstage/backend-app-api/dist/index.cjs.js:1611:5)
    at async BackstageBackend.start (/opt/app-root/src/node_modules/@backstage/backend-app-api/dist/index.cjs.js:1881:5) {
  cause: Error: Missing required config value at 'catalog.providers.githubOrg.githubUrl'
      at ConfigReader.getString (/opt/app-root/src/node_modules/@backstage/config/dist/index.cjs.js:305:13)
      at ObservableConfigProxy.getString (/opt/app-root/src/node_modules/@backstage/config-loader/dist/index.cjs.js:1348:30)
      at /opt/app-root/src/dynamic-plugins-root/backstage-plugin-catalog-backend-module-github-org-dynamic-0.1.6/dist/index.cjs.js:2561:19
      at Array.map (<anonymous>)
      at readDefinitionsFromConfig (/opt/app-root/src/dynamic-plugins-root/backstage-plugin-catalog-backend-module-github-org-dynamic-0.1.6/dist/index.cjs.js:2559:19)
      at Object.init [as func] (/opt/app-root/src/dynamic-plugins-root/backstage-plugin-catalog-backend-module-github-org-dynamic-0.1.6/dist/index.cjs.js:2533:35)
      at /opt/app-root/src/node_modules/@backstage/backend-app-api/dist/index.cjs.js:1780:35
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async processNode (/opt/app-root/src/node_modules/@backstage/backend-app-api/dist/index.cjs.js:1302:22)
      at async Promise.all (index 3)
      at async processMoreNodes (/opt/app-root/src/node_modules/@backstage/backend-app-api/dist/index.cjs.js:1297:7)
      at async _DependencyGraph.parallelTopologicalTraversal (/opt/app-root/src/node_modules/@backstage/backend-app-api/dist/index.cjs.js:1308:5)
      at async /opt/app-root/src/node_modules/@backstage/backend-app-api/dist/index.cjs.js:1777:9
      at async Promise.all (index 1)
      at async BackendInitializer.doStart_fn (/opt/app-root/src/node_modules/@backstage/backend-app-api/dist/index.cjs.js:1757:3)
      at async BackendInitializer.start (/opt/app-root/src/node_modules/@backstage/backend-app-api/dist/index.cjs.js:1611:5)
}

Node.js v18.18.2
```
